// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/podis-pickles/Cart.tsx": () => import("../components/mockups/podis-pickles/Cart.tsx"),
  "./components/mockups/podis-pickles/Checkout.tsx": () => import("../components/mockups/podis-pickles/Checkout.tsx"),
  "./components/mockups/podis-pickles/Discover.tsx": () => import("../components/mockups/podis-pickles/Discover.tsx"),
  "./components/mockups/podis-pickles/Home.tsx": () => import("../components/mockups/podis-pickles/Home.tsx"),
  "./components/mockups/podis-pickles/ProductDetail.tsx": () => import("../components/mockups/podis-pickles/ProductDetail.tsx"),
  "./components/mockups/podis-pickles/Welcome.tsx": () => import("../components/mockups/podis-pickles/Welcome.tsx")
};
